import type { Scenario } from './types'

export const SCENARIOS: Scenario[] = [
  {
    id: 'supermarket',
    name: 'The Supermarket',
    emoji: '🛒',
    description: 'Navigate a large supermarket, find your items, and help someone in need.',
    setting: `You're in a medium-sized supermarket — clean, well-lit, but without any visible aisle signs. The store has about 20 shoppers moving around. There's a faint smell of fresh bread from the bakery at the back. You need to find specific grocery items before you can check out.`,
    difficulty: 'beginner',
    bgGradient: 'from-emerald-950 to-game-bg',
    npcs: [
      {
        id: 'store-employee',
        name: 'Maria',
        age: 38,
        role: 'Store Employee',
        avatarEmoji: '👩‍💼',
        personality: 'Friendly, efficient, knowledgeable about the whole store. She has worked here 8 years. Warm but slightly rushed — she has a trolley she is restocking. Will give very precise directions if asked well.',
        currentSituation: 'Restocking tinned goods in aisle 4. She is placing cans of tomatoes onto a shelf.',
        knowledge: ['knows exactly where everything is', 'knows about current promotions', 'knows the store layout inside out'],
        mood: 'busy',
      },
      {
        id: 'couple',
        name: 'Tom & Sarah',
        age: 34,
        role: 'Shoppers (couple)',
        avatarEmoji: '👫',
        personality: 'A couple, mid-30s, with a young child in the trolley. Tom is quiet and deferential. Sarah is warmer and more talkative. They shop here occasionally — familiar but not regulars. They will try to help but only know roughly where things are.',
        currentSituation: 'Debating which cereal to buy, their toddler is getting restless. They look slightly frazzled.',
        knowledge: ['vaguely knows the layout from previous visits', 'thinks canned goods are toward the back', 'is not sure where coconut products are'],
        mood: 'neutral',
      },
      {
        id: 'old-man',
        name: 'Jim',
        age: 72,
        role: 'Regular Shopper',
        avatarEmoji: '👴',
        personality: 'A retired man, very chatty and loves a conversation. He is a genuine regular here — knows the store extremely well. He is a bit slow to get to the point but genuinely helpful. Will share unsolicited anecdotes. Gets a bit lonely.',
        currentSituation: 'Reading the label on a tin of soup very carefully, slightly hunched over.',
        knowledge: ['knows the store better than most employees', 'shops here every Tuesday and Thursday', 'knows all the staff by name'],
        mood: 'friendly',
      },
      {
        id: 'young-professional',
        name: 'Priya',
        age: 27,
        role: 'Young Professional',
        avatarEmoji: '👩‍💻',
        personality: 'A young professional in work clothes, clearly on a lunch break. Constantly checking her phone. Somewhat distracted and a little anxious. She is not unfriendly but will give short answers. She appreciates directness.',
        currentSituation: 'Standing near the entrance to the produce section, staring at her shopping list on her phone with a furrowed brow. She looks lost.',
        knowledge: ['does not shop here often', 'does not know the layout at all'],
        mood: 'stressed',
        needsHelp: 'She cannot find the coconut milk and is worried her lunch break is almost over.',
        helpSignals: ['repeatedly glancing at her phone then looking around confused', 'sighing quietly', 'standing still in an aisle looking uncertain'],
      },
      {
        id: 'manager',
        name: 'Dave',
        age: 45,
        role: 'Store Manager',
        avatarEmoji: '👨‍💼',
        personality: 'The store manager — friendly, professional, authoritative. He knows everything about the store. He is walking the floor doing a check. He is approachable but clearly mid-task.',
        currentSituation: 'Walking purposefully between aisles with a clipboard, doing a stock check.',
        knowledge: ['knows every inch of the store', 'knows all current stock levels', 'knows about the new layout changes'],
        mood: 'busy',
      },
    ],
    objectives: [
      {
        id: 'find-chickpeas',
        description: 'Find canned chickpeas',
        type: 'primary',
        completionHint: 'Ask someone where the canned goods or chickpeas are',
      },
      {
        id: 'find-potatoes',
        description: 'Find 300–500g potatoes',
        type: 'primary',
        completionHint: 'Ask someone where the produce/vegetable section is',
      },
      {
        id: 'find-tomatoes',
        description: 'Find 300–500g tomatoes (fresh or tinned)',
        type: 'primary',
        completionHint: 'Ask about the tomatoes in produce or tinned goods',
      },
      {
        id: 'find-coconut',
        description: 'Find coconut powder or coconut milk',
        type: 'primary',
        completionHint: 'Ask where international/ethnic foods or baking ingredients are',
      },
      {
        id: 'help-priya',
        description: 'Help someone in need',
        type: 'bonus',
        completionHint: 'Notice Priya looks lost and offer to help her find something',
      },
    ],
    chanceEvents: [
      {
        id: 'bumped-into-jim',
        triggerAfterMessages: 6,
        description: 'Jim approaches you directly',
        npcId: 'old-man',
        npcMessage: 'Oh! Excuse me, young one — sorry to bother you, but I wonder if you could help me reach that tin up there? My back\'s not what it used to be...',
      },
    ],
    tips: [
      'Start conversations with "Excuse me" or "Sorry to bother you"',
      'Read body language — some people are in a rush',
      'Always thank people after they help you',
      'Look around before asking — can you spot any helpful signs or people?',
    ],
  },
  {
    id: 'underground',
    name: 'London Underground',
    emoji: '🚇',
    description: 'Navigate the Tube during rush hour, get directions, and handle unexpected situations.',
    setting: `It's 8:45am on a Tuesday at a busy Central London Tube station. Commuters stream past in every direction. The electronic boards are showing delays on two lines. You need to get to a job interview across town but you are unfamiliar with this station.`,
    difficulty: 'intermediate',
    bgGradient: 'from-blue-950 to-game-bg',
    npcs: [
      {
        id: 'ticket-officer',
        name: 'Marcus',
        age: 44,
        role: 'Ticket Office Officer',
        avatarEmoji: '🧑‍✈️',
        personality: 'A TfL employee with 15 years experience. Knowledgeable and direct. Not unfriendly but has seen everything and takes no nonsense. Will give excellent, precise directions if you engage respectfully. Slightly impatient during rush hour.',
        currentSituation: 'Sitting at the ticket office window, handling a queue. Currently between customers.',
        knowledge: ['knows all lines, connections, and fastest routes', 'knows about the current delays', 'knows every exit of this station'],
        mood: 'neutral',
      },
      {
        id: 'regular-commuter',
        name: 'Janet',
        age: 52,
        role: 'Regular Commuter',
        avatarEmoji: '👩',
        personality: 'A professional woman who commutes this route every day. She knows it well. She is in a hurry but has a kind face. She will help briefly if asked politely. She is listening to a podcast but her earphones are only in one ear.',
        currentSituation: 'Walking purposefully toward the Northern line platform, rolling a small suitcase.',
        knowledge: ['knows this station well', 'knows how to avoid the delays today', 'knows good connecting routes'],
        mood: 'busy',
      },
      {
        id: 'tourist',
        name: 'Hiroshi',
        age: 29,
        role: 'Tourist',
        avatarEmoji: '🧑‍🦱',
        personality: 'A Japanese tourist, friendly and eager. His English is good but not perfect. He has a tube map out and is studying it intensely. He is lost but in good spirits about it. He will be very grateful if you help him.',
        currentSituation: 'Standing by a pillar, unfolding and refolding the free Tube map, looking at the board, then back at the map.',
        knowledge: ['has a Tube map', 'is confused about line colours', 'is looking for the Natural History Museum'],
        mood: 'confused',
        needsHelp: 'He is on the wrong platform and is about to get on a train going in completely the wrong direction.',
        helpSignals: ['studying map intensely', 'looking at the wrong platform board', 'muttering quietly to himself in Japanese'],
      },
      {
        id: 'busker',
        name: 'Leo',
        age: 23,
        role: 'Busker',
        avatarEmoji: '🎸',
        personality: 'A young busker with a guitar, warm and talkative. He busks here every morning and knows the station layout perfectly — surprisingly good local knowledge. He is chatty and will gladly talk if you engage him.',
        currentSituation: 'Taking a short break from playing, drinking from a thermos.',
        knowledge: ['knows all exits and platforms', 'knows the fastest route to most central London stations', 'knows which carriages are quietest'],
        mood: 'friendly',
      },
      {
        id: 'lost-older-woman',
        name: 'Eileen',
        age: 69,
        role: 'Infrequent Traveller',
        avatarEmoji: '👵',
        personality: 'An older woman who does not use the Tube often. She is polite and slightly flustered. She is not in distress but clearly needs guidance. She responds very warmly to patience and kindness.',
        currentSituation: 'Standing near the barriers with a paper ticket, looking at the barriers with slight uncertainty, then at a helper-point phone she has not picked up.',
        knowledge: ['does not know the station', 'has a valid ticket but is unsure how to use the barriers'],
        mood: 'stressed',
        needsHelp: 'She cannot figure out how to use the Tube barriers with her paper ticket and is too embarrassed to ask.',
        helpSignals: ['staring at the barriers repeatedly', 'holding her ticket tightly', 'hesitating to go through'],
      },
    ],
    objectives: [
      {
        id: 'find-right-line',
        description: 'Find out which line to take to get to Bank station',
        type: 'primary',
        completionHint: 'Ask someone which line goes to Bank',
      },
      {
        id: 'handle-delay',
        description: 'Find out how to avoid the current delays',
        type: 'primary',
        completionHint: 'Ask about the delays showing on the board',
      },
      {
        id: 'find-exit',
        description: 'Find out which exit to use at Bank for Threadneedle Street',
        type: 'primary',
        completionHint: 'Ask about the exit at Bank station',
      },
      {
        id: 'help-hiroshi',
        description: 'Help the confused tourist',
        type: 'bonus',
        completionHint: 'Notice Hiroshi is on the wrong platform and point him in the right direction',
      },
      {
        id: 'help-eileen',
        description: 'Help the older traveller with the barriers',
        type: 'bonus',
        completionHint: 'Offer to help Eileen with her paper ticket',
      },
    ],
    chanceEvents: [
      {
        id: 'train-announcement',
        triggerAfterMessages: 5,
        description: 'Eileen approaches you looking worried',
        npcId: 'lost-older-woman',
        npcMessage: 'Oh, sorry dear — I hate to bother you, but I can\'t seem to work this wretched machine. Is it the yellow line I tap, or...? I\'ve got a paper ticket, you see.',
      },
    ],
    tips: [
      'People in London are busy — be brief and direct when asking questions',
      'A smile goes a long way, even with strangers',
      'Look around before interrupting someone — are they on the phone?',
      'If someone helps you, a simple "thank you, that\'s really helpful" makes a big difference',
    ],
  },
  {
    id: 'birthday-party',
    name: "Friend's Birthday Party",
    emoji: '🎉',
    description: "You only know the birthday person. Navigate a room full of strangers and make real connections.",
    setting: `It's a house party for your friend Alex's 30th birthday. About 25 people are here — a mix of Alex's uni friends, work colleagues, and family. You only know Alex, who is currently busy hosting. The flat is buzzing with conversation and background music. You've been standing near the drinks table for a few minutes.`,
    difficulty: 'advanced',
    bgGradient: 'from-purple-950 to-game-bg',
    npcs: [
      {
        id: 'extrovert-friend',
        name: 'Charlie',
        age: 31,
        role: "Alex's Uni Friend",
        avatarEmoji: '🙋‍♂️',
        personality: 'Hugely extroverted, loves meeting new people. He will talk to anyone. Slightly over-the-top energy, but genuinely warm. He will happily draw you into a conversation and introduce you around if you engage with him.',
        currentSituation: 'Standing nearby, scanning the room, clearly looking for someone to talk to. He catches your eye and gives a nod.',
        knowledge: ['knows many people at the party', 'knows lots of stories about Alex'],
        mood: 'friendly',
      },
      {
        id: 'work-colleague',
        name: 'Sophie',
        age: 29,
        role: "Alex's Work Colleague",
        avatarEmoji: '👩‍🔬',
        personality: 'Quiet, thoughtful, professionally-minded. Works in tech. She finds small talk a little tedious but lights up when conversation goes deeper. She is not cold — just needs a genuine question or topic to engage with. She appreciates people who listen.',
        currentSituation: 'Standing by the bookshelf, reading the titles. She looks content but slightly separate from the main group.',
        knowledge: ['works with Alex', 'knows about the tech industry'],
        mood: 'neutral',
      },
      {
        id: 'alexs-cousin',
        name: 'Remi',
        age: 22,
        role: "Alex's Cousin",
        avatarEmoji: '🧑',
        personality: 'Younger, slightly nervous at a party where he knows almost nobody. A bit awkward but really wants to have a good time. He would be extremely grateful for conversation. He has great taste in music and gaming.',
        currentSituation: 'Sitting on a chair near the edge of the room, nursing a drink and scrolling his phone.',
        knowledge: ['knows Alex from family gatherings', 'does not know most people here'],
        mood: 'neutral',
        needsHelp: 'He is feeling out of place and would love someone to include him in a conversation.',
        helpSignals: ['sitting alone on the edge of the group', 'repeatedly checking his phone', 'looking up at conversations he is not part of'],
      },
      {
        id: 'alexs-mum',
        name: "Pat (Alex's Mum)",
        age: 58,
        role: "Alex's Parent",
        avatarEmoji: '👩‍🦳',
        personality: 'Alex\'s mum, absolutely lovely. Very proud of Alex. Loves talking about Alex\'s childhood. Warm, maternal, talks a lot. Responds brilliantly to genuine questions about the family. Will try to feed you.',
        currentSituation: 'Standing near the food table, arranging nibbles that do not need rearranging.',
        knowledge: ['knows everything about Alex growing up', 'knows most of Alex\'s family friends'],
        mood: 'friendly',
      },
      {
        id: 'confident-stranger',
        name: 'Jess',
        age: 33,
        role: 'Friend of a Friend',
        avatarEmoji: '💁‍♀️',
        personality: 'Confident, sharp, funny. She tests people a little — gives slightly short answers at first to see if you are worth talking to. If you hold your own and show genuine interest, she becomes very engaging. She has had a few drinks and is in a good mood.',
        currentSituation: 'In the middle of the room, between conversations, holding a glass of wine and looking slightly amused at the room.',
        knowledge: ['knows a few people here', 'came with Sophie'],
        mood: 'neutral',
      },
    ],
    objectives: [
      {
        id: 'introduce-yourself',
        description: 'Introduce yourself to at least 2 new people',
        type: 'primary',
        completionHint: 'Start conversations with at least 2 different people and tell them your name',
      },
      {
        id: 'find-common-ground',
        description: 'Find something in common with someone',
        type: 'primary',
        completionHint: 'Discover a shared interest, place, or experience with someone',
      },
      {
        id: 'keep-conversation-going',
        description: 'Hold a conversation for more than 3 exchanges without it dying',
        type: 'primary',
        completionHint: 'Ask follow-up questions and keep a natural back-and-forth going',
      },
      {
        id: 'help-remi',
        description: 'Include the person sitting alone',
        type: 'bonus',
        completionHint: 'Notice Remi sitting by himself and bring him into a conversation or just chat with him',
      },
    ],
    chanceEvents: [
      {
        id: 'awkward-silence',
        triggerAfterMessages: 8,
        description: 'Charlie unexpectedly introduces you to someone mid-conversation',
        npcId: 'extrovert-friend',
        npcMessage: 'Oh! You have GOT to meet Sophie — Sophie! SOPHIE! Come over here, this person is brilliant, you two will love each other.',
      },
    ],
    tips: [
      'At parties, people appreciate being approached — most people want to talk',
      'Ask open questions ("How do you know Alex?") not closed ones ("Do you know Alex?")',
      'Remember details people share — mentioning them later shows you were listening',
      'It is completely normal to feel nervous. Most people feel the same way.',
    ],
  },
]

export function getScenario(id: string): Scenario | undefined {
  return SCENARIOS.find(s => s.id === id)
}

export function getNPC(scenario: Scenario, npcId: string) {
  return scenario.npcs.find(n => n.id === npcId)
}
