import type { Scenario } from './types'

export const SCENARIOS: Scenario[] = [
  {
    id: 'supermarket',
    name: 'The Supermarket',
    emoji: '🛒',
    description: 'Navigate a large supermarket, find your items, and help someone in need.',
    setting: `You're in a medium-sized supermarket — clean, well-lit, but without any visible aisle signs. The store has about 20 shoppers moving around. There's a faint smell of fresh bread from the bakery at the back. You need to find specific grocery items before you can check out.`,
    difficulty: 'beginner',
    bgGradient: 'from-emerald-950 to-game-bg',
    npcs: [
      {
        id: 'store-employee',
        name: 'Maria',
        age: 38,
        role: 'Store Employee',
        avatarEmoji: '👩‍💼',
        personality: 'Friendly, efficient, knowledgeable about the whole store. She has worked here 8 years. Warm but slightly rushed — she has a trolley she is restocking. Will give very precise directions if asked well.',
        currentSituation: 'Restocking tinned goods in aisle 4. She is placing cans of tomatoes onto a shelf.',
        knowledge: ['knows exactly where everything is', 'knows about current promotions', 'knows the store layout inside out'],
        mood: 'busy',
        gender: 'female', hairStyle: 'ponytail', hairColor: '#3a2210', skinTone: '#d4956a',
      },
      {
        id: 'couple',
        name: 'Tom & Sarah',
        age: 34,
        role: 'Shoppers (couple)',
        avatarEmoji: '👫',
        personality: 'A couple, mid-30s, with a young child in the trolley. Tom is quiet and deferential. Sarah is warmer and more talkative. They shop here occasionally — familiar but not regulars. They will try to help but only know roughly where things are.',
        currentSituation: 'Debating which cereal to buy, their toddler is getting restless. They look slightly frazzled.',
        knowledge: ['vaguely knows the layout from previous visits', 'thinks canned goods are toward the back', 'is not sure where coconut products are'],
        mood: 'neutral',
        gender: 'female', hairStyle: 'wavy', hairColor: '#c8a020', skinTone: '#f2d4a8',
      },
      {
        id: 'old-man',
        name: 'Jim',
        age: 72,
        role: 'Regular Shopper',
        avatarEmoji: '👴',
        personality: 'A retired man, very chatty and loves a conversation. He is a genuine regular here — knows the store extremely well. He is a bit slow to get to the point but genuinely helpful. Will share unsolicited anecdotes. Gets a bit lonely.',
        currentSituation: 'Reading the label on a tin of soup very carefully, slightly hunched over.',
        knowledge: ['knows the store better than most employees', 'shops here every Tuesday and Thursday', 'knows all the staff by name'],
        mood: 'friendly',
        gender: 'male', hairStyle: 'bald', skinTone: '#e8c090',
      },
      {
        id: 'young-professional',
        name: 'Priya',
        age: 27,
        role: 'Young Professional',
        avatarEmoji: '👩‍💻',
        personality: 'A young professional in work clothes, clearly on a lunch break. Constantly checking her phone. Somewhat distracted and a little anxious. She is not unfriendly but will give short answers. She appreciates directness.',
        currentSituation: 'Standing near the entrance to the produce section, staring at her shopping list on her phone with a furrowed brow. She looks lost.',
        knowledge: ['does not shop here often', 'does not know the layout at all'],
        mood: 'stressed',
        needsHelp: 'She cannot find the coconut milk and is worried her lunch break is almost over.',
        helpSignals: ['repeatedly glancing at her phone then looking around confused', 'sighing quietly', 'standing still in an aisle looking uncertain'],
        gender: 'female', hairStyle: 'long', hairColor: '#1a0800', skinTone: '#8b5e3c',
      },
      {
        id: 'manager',
        name: 'Dave',
        age: 45,
        role: 'Store Manager',
        avatarEmoji: '👨‍💼',
        personality: 'The store manager — friendly, professional, authoritative. He knows everything about the store. He is walking the floor doing a check. He is approachable but clearly mid-task.',
        currentSituation: 'Walking purposefully between aisles with a clipboard, doing a stock check.',
        knowledge: ['knows every inch of the store', 'knows all current stock levels', 'knows about the new layout changes'],
        mood: 'busy',
        gender: 'male', hairStyle: 'short', hairColor: '#555555', skinTone: '#e0b888',
      },
    ],
    objectives: [
      {
        id: 'find-chickpeas',
        description: 'Find canned chickpeas',
        type: 'primary',
        completionHint: 'Ask someone where the canned goods or chickpeas are',
      },
      {
        id: 'find-potatoes',
        description: 'Find 300–500g potatoes',
        type: 'primary',
        completionHint: 'Ask someone where the produce/vegetable section is',
      },
      {
        id: 'find-tomatoes',
        description: 'Find 300–500g tomatoes (fresh or tinned)',
        type: 'primary',
        completionHint: 'Ask about the tomatoes in produce or tinned goods',
      },
      {
        id: 'find-coconut',
        description: 'Find coconut powder or coconut milk',
        type: 'primary',
        completionHint: 'Ask where international/ethnic foods or baking ingredients are',
      },
      {
        id: 'help-priya',
        description: 'Help someone in need',
        type: 'bonus',
        completionHint: 'Notice Priya looks lost and offer to help her find something',
      },
    ],
    chanceEvents: [
      {
        id: 'bumped-into-jim',
        triggerAfterMessages: 9999,   // disabled — Jim greets via proximity trigger instead
        description: 'Jim approaches you directly',
        npcId: 'old-man',
        npcMessage: 'Oh! Excuse me, young one — sorry to bother you, but I wonder if you could help me reach that tin up there? My back\'s not what it used to be...',
      },
    ],
    tips: [
      'Start conversations with "Excuse me" or "Sorry to bother you"',
      'Read body language — some people are in a rush',
      'Always thank people after they help you',
      'Look around before asking — can you spot any helpful signs or people?',
    ],
  },
  {
    id: 'underground',
    name: 'London Underground',
    emoji: '🚇',
    description: 'Navigate a maze-like tube station to find the right platform and board the correct train.',
    setting: `You're at Shepherd's Bush Market Underground station, needing to get to High Street Kensington. The station is a maze of corridors leading to two platforms — but you don't know which line, which direction, or which platform to use. There's no signal on your phone, the signs are confusing, and a train is due soon. You need to ask the right people before you miss it.`,
    difficulty: 'intermediate',
    bgGradient: 'from-blue-950 to-game-bg',
    npcs: [
      {
        id: 'ticket-officer',
        name: 'Marcus',
        age: 44,
        role: 'Ticket Office Officer',
        avatarEmoji: '🧑‍✈️',
        personality: 'A TfL employee with 15 years\' experience at this station. Direct, efficient, and unflappable. He has seen every possible tourist question and is surprisingly patient about it. He will give excellent, precise directions if you engage respectfully — he takes his job seriously.',
        currentSituation: 'Sitting in the ticket office booth behind a glass window, monitoring the barriers. He is between customers and scanning the concourse with a practiced eye.',
        knowledge: ['knows exactly that Platform 1 is eastbound toward High Street Kensington and beyond', 'knows that Platform 2 is westbound toward Hammersmith — the wrong direction', 'knows the Hammersmith & City and Circle lines both stop here', 'can give clear directions to Platform 1 through the right-hand corridor'],
        mood: 'neutral',
        gender: 'male', hairStyle: 'short', hairColor: '#222222', skinTone: '#5a3820',
      },
      {
        id: 'regular-commuter',
        name: 'Janet',
        age: 52,
        role: 'Regular Commuter',
        avatarEmoji: '👩',
        personality: 'A professional woman who commutes this exact route five days a week. She is in a hurry but has a kind face. She will give brief, accurate answers if you ask directly — she does not have time for small talk. Earphones in one ear.',
        currentSituation: 'Walking purposefully toward the right-hand corridor (the one that leads to Platform 1, eastbound). She is clearly on her way to work.',
        knowledge: ['knows Platform 1 is the eastbound platform — right-hand corridor', 'knows the next eastbound train is in a few minutes', 'knows Platform 2 is the wrong direction for central London'],
        mood: 'busy',
        gender: 'female', hairStyle: 'medium', hairColor: '#704020', skinTone: '#d4a070',
      },
      {
        id: 'tourist',
        name: 'Hiroshi',
        age: 29,
        role: 'Tourist',
        avatarEmoji: '🧑‍🦱',
        personality: 'A Japanese tourist visiting London for the first time. Friendly and enthusiastic, his English is good. He has a Tube map and is trying hard to understand it. He is in good spirits despite being lost. He will be genuinely grateful if someone helps him.',
        currentSituation: 'Standing in the ticket hall staring at the wall map, moving his finger along the lines and looking puzzled. He needs to get to Ladbroke Grove but is about to walk to the wrong platform.',
        knowledge: ['has a tube map but finds the line colours confusing', 'does not know which platform to use for any destination', 'knows he needs the Hammersmith and City line but not which direction'],
        mood: 'confused',
        needsHelp: 'He is about to take Platform 2 (westbound) to get to Ladbroke Grove but needs Platform 1 (eastbound — Ladbroke Grove is one stop east).',
        helpSignals: ['studying the wall map intensely, tracing routes with his finger', 'looking back and forth between map and the corridor signs', 'taking a tentative step toward the left-hand (wrong) corridor then stopping'],
        gender: 'male', hairStyle: 'short', hairColor: '#0a0a0a', skinTone: '#d8b890',
      },
      {
        id: 'busker',
        name: 'Leo',
        age: 23,
        role: 'Busker',
        avatarEmoji: '🎸',
        personality: 'A young busker who plays here every morning. Warm, relaxed, and surprisingly knowledgeable about the station — he knows it better than most staff. He is happy to chat and genuinely enjoys helping people navigate.',
        currentSituation: 'Taking a break near the station entrance, sitting on his guitar case with a coffee, people-watching.',
        knowledge: ['knows Platform 1 is the right-hand corridor — eastbound', 'knows the Hammersmith & City line is the one to take', 'knows Marcus in the ticket office is the most helpful person here', 'knows roughly how long until the next train'],
        mood: 'friendly',
        gender: 'male', hairStyle: 'wavy', hairColor: '#8b4513', skinTone: '#c8956a',
      },
      {
        id: 'lost-older-woman',
        name: 'Eileen',
        age: 69,
        role: 'Infrequent Traveller',
        avatarEmoji: '👵',
        personality: 'An older woman who has not used the Tube in several years. She is polite, slightly flustered, and a little embarrassed about not knowing what to do. She responds very warmly to patience and kindness, and is clearly relieved when someone offers to help.',
        currentSituation: 'Standing at the ticket barriers holding a paper ticket, staring at the gate and then at the ticket, unsure which slot to put it in.',
        knowledge: ['does not know the station at all', 'has a valid paper ticket but does not know how to use the barriers', 'is not sure which platform she needs either'],
        mood: 'stressed',
        needsHelp: 'She cannot figure out how to insert her paper ticket into the barrier gate.',
        helpSignals: ['looking repeatedly from ticket to barrier slot', 'holding her ticket tightly', 'tentatively reaching toward the barrier then pulling back'],
        gender: 'female', hairStyle: 'short', hairColor: '#c8c8c8', skinTone: '#e8c8a8',
      },
    ],
    objectives: [
      {
        id: 'find-correct-line',
        description: 'Find out which line goes to High Street Kensington',
        type: 'primary',
        completionHint: 'Ask someone which tube line stops at High Street Kensington',
      },
      {
        id: 'find-correct-platform',
        description: 'Find out which platform to use (eastbound)',
        type: 'primary',
        completionHint: 'Ask someone which platform or direction to take',
      },
      {
        id: 'board-train',
        description: 'Board the correct train on Platform 1',
        type: 'primary',
        completionHint: 'Navigate to Platform 1 (right-hand corridor) and board the eastbound train',
      },
      {
        id: 'help-hiroshi',
        description: 'Help the confused tourist heading the wrong way',
        type: 'bonus',
        completionHint: 'Notice Hiroshi is about to take the wrong platform and point him to Platform 1',
      },
      {
        id: 'help-eileen',
        description: 'Help the older traveller with the ticket barriers',
        type: 'bonus',
        completionHint: 'Offer to help Eileen figure out how to use her paper ticket',
      },
    ],
    chanceEvents: [
      {
        id: 'eileen-at-barriers',
        triggerAfterMessages: 9999,   // disabled — proximity trigger fires when player walks near her
        description: 'Eileen notices you and asks for help',
        npcId: 'lost-older-woman',
        npcMessage: 'Oh, excuse me — I\'m so sorry to bother you, but I can\'t for the life of me work out how to get through this thing. Is it this slot here? I\'ve got a paper ticket, you see...',
      },
    ],
    tips: [
      'People in London are busy — be brief and direct',
      'The ticket office is the most reliable source of information',
      'Look around — do any signs or people give you clues about which way to go?',
      'If someone helps you, a warm "thank you" goes a long way',
    ],
  },
  {
    id: 'birthday-party',
    name: "Friend's Birthday Party",
    emoji: '🎉',
    description: "You only know the birthday person. Explore three rooms, meet strangers, and make real connections.",
    setting: `It's Alex's 30th birthday party in their South London flat. About 25 people are spread across the living room, kitchen, and garden. You only know Alex, who is currently busy hosting. The flat buzzes with overlapping conversations — different groups in each room. You've just arrived through the front door.`,
    difficulty: 'advanced',
    bgGradient: 'from-purple-950 to-game-bg',
    npcs: [
      {
        id: 'extrovert-friend',
        name: 'Charlie',
        age: 31,
        role: "Alex's Uni Friend",
        avatarEmoji: '🙋‍♂️',
        personality: 'Hugely extroverted, loves meeting new people. Slightly over-the-top energy but genuinely warm. He gravitates toward anyone who looks new and will happily introduce you around if you engage with him. Knows almost everyone here.',
        currentSituation: 'Standing near the drinks area in the living room, scanning the room for someone to talk to. He spots you almost immediately.',
        knowledge: ['knows most people at the party', 'knows many stories about Alex', 'knows who is in the kitchen and garden'],
        mood: 'friendly',
        gender: 'male', hairStyle: 'short', hairColor: '#b87820', skinTone: '#e8c090',
      },
      {
        id: 'work-colleague',
        name: 'Sophie',
        age: 29,
        role: "Alex's Work Colleague",
        avatarEmoji: '👩‍🔬',
        personality: 'Quiet, thoughtful, professionally-minded. Works in tech. Finds small talk a bit tedious but lights up when conversation goes deeper. Not cold — just needs a genuine question to engage. Appreciates people who actually listen.',
        currentSituation: 'Standing by the bookshelf in the living room, reading the titles with genuine interest. She is slightly separate from the main group.',
        knowledge: ['works with Alex in tech', 'knows about the industry', 'came with Jess'],
        mood: 'neutral',
        gender: 'female', hairStyle: 'ponytail', hairColor: '#1a1a1a', skinTone: '#f0c8a0',
      },
      {
        id: 'alexs-cousin',
        name: 'Remi',
        age: 22,
        role: "Alex's Cousin",
        avatarEmoji: '🧑',
        personality: 'Younger, slightly nervous at a party where he knows almost nobody. A bit awkward but genuinely wants to have a good time. Would be extremely grateful for conversation. Great taste in music and gaming — if you find the right topic, he opens right up.',
        currentSituation: 'Sitting on a chair near the edge of the living room, nursing a drink and scrolling his phone. He looks up occasionally at other conversations.',
        knowledge: ['knows Alex from family events', 'does not know most people at the party'],
        mood: 'neutral',
        needsHelp: 'He is feeling out of place and would love someone to include him.',
        helpSignals: ['sitting alone at the edge of the room', 'repeatedly checking his phone', 'glancing up at conversations he is not part of'],
        gender: 'male', hairStyle: 'afro', hairColor: '#1a0800', skinTone: '#5a3820',
      },
      {
        id: 'alexs-mum',
        name: 'Pat',
        age: 58,
        role: "Alex's Mum",
        avatarEmoji: '👩‍🦳',
        personality: 'Alex\'s mum — absolutely lovely, very proud of Alex. Loves talking about Alex\'s childhood and achievements. Warm, maternal, talks a lot. Responds brilliantly to genuine questions about the family. Will try to feed you.',
        currentSituation: 'In the kitchen, arranging party food on plates that do not really need rearranging. She is clearly in her element.',
        knowledge: ['knows everything about Alex growing up', 'knows most of Alex\'s family', 'knows who is in each room'],
        mood: 'friendly',
        gender: 'female', hairStyle: 'short', hairColor: '#d8d0c0', skinTone: '#e0b888',
      },
      {
        id: 'confident-stranger',
        name: 'Jess',
        age: 33,
        role: 'Friend of a Friend',
        avatarEmoji: '💁‍♀️',
        personality: 'Confident, sharp, funny. Tests people slightly at first — gives short answers to see if you\'re worth talking to. If you hold your own and show genuine interest, she becomes very engaging and warm. Has had a couple of drinks and is in a great mood.',
        currentSituation: 'Standing in the middle of the living room between conversations, holding a glass of wine and looking slightly amused at the room.',
        knowledge: ['knows a few people here', 'came with Sophie', 'works in advertising'],
        mood: 'neutral',
        gender: 'female', hairStyle: 'long', hairColor: '#c84820', skinTone: '#f0d0b0',
      },
      {
        id: 'quiet-garden-friend',
        name: 'Sam',
        age: 35,
        role: "Alex's Colleague",
        avatarEmoji: '🧑‍💻',
        personality: 'Quiet, introverted, but genuinely warm once you get past the initial quietness. Has a dry, understated sense of humour. Works with Alex and knows him well. Came outside to get some air from the crowd. Appreciates anyone who takes the time to talk properly.',
        currentSituation: 'Sitting alone at the patio table in the garden with a drink, looking up at the stars. He\'s happy to be outside away from the noise.',
        knowledge: ['knows Alex well from work', 'knows Sophie from the office too', 'has interesting opinions about technology and society'],
        mood: 'neutral',
        gender: 'male', hairStyle: 'medium', hairColor: '#5a3a1a', skinTone: '#e8c090',
      },
      {
        id: 'loud-neighbour',
        name: 'Bea',
        age: 42,
        role: "Alex's Neighbour",
        avatarEmoji: '🙋‍♀️',
        personality: 'The downstairs neighbour — gregarious, loud, and absolutely delightful. She was not originally invited but turned up anyway and has become the life of the kitchen. Knows a lot of the local gossip. Very easy to talk to — she will talk to literally anyone.',
        currentSituation: 'Holding court in the kitchen, telling a story to anyone who will listen. She breaks off mid-sentence to greet you if you enter.',
        knowledge: ['knows the local neighbourhood very well', 'knows a bit about everyone at the party already', 'knows where Alex keeps the good wine'],
        mood: 'friendly',
        gender: 'female', hairStyle: 'wavy', hairColor: '#cc4422', skinTone: '#d4a070',
      },
      {
        id: 'alexs-sibling',
        name: 'Jordan',
        age: 26,
        role: "Alex's Sibling",
        avatarEmoji: '🧑',
        personality: 'Alex\'s younger sibling, helping host the party. Slightly frantic but in a good way — clearly loves Alex and wants tonight to be special. Friendly and genuine, will chat briefly between tasks. Can tell you a lot about Alex.',
        currentSituation: 'Moving between the living room and kitchen helping with drinks and food, clearly on a mission.',
        knowledge: ['knows Alex extremely well — grew up together', 'knows who is at the party and where they are', 'is managing the music playlist'],
        mood: 'busy',
        gender: 'male', hairStyle: 'short', hairColor: '#2a1a08', skinTone: '#8b5e3c',
      },
    ],
    objectives: [
      {
        id: 'introduce-yourself',
        description: 'Introduce yourself to at least 2 new people',
        type: 'primary',
        completionHint: 'Start conversations with at least 2 different people and tell them your name',
      },
      {
        id: 'find-common-ground',
        description: 'Find something in common with someone',
        type: 'primary',
        completionHint: 'Discover a shared interest, place, or experience with someone',
      },
      {
        id: 'keep-conversation-going',
        description: 'Hold a conversation for more than 3 exchanges without it dying',
        type: 'primary',
        completionHint: 'Ask follow-up questions and keep a natural back-and-forth going',
      },
      {
        id: 'help-remi',
        description: 'Include the person sitting alone',
        type: 'bonus',
        completionHint: 'Notice Remi sitting by himself and bring him into a conversation',
      },
      {
        id: 'learn-about-alex',
        description: 'Learn something personal about Alex from a family member',
        type: 'bonus',
        completionHint: 'Ask Pat or Jordan something genuine about Alex',
      },
    ],
    chanceEvents: [
      {
        id: 'charlie-introduction',
        triggerAfterMessages: 8,
        description: 'Charlie enthusiastically introduces you to Sophie',
        npcId: 'extrovert-friend',
        npcMessage: 'Oh! You have GOT to meet Sophie — Sophie! SOPHIE! Come over here, this person is brilliant, you two will love each other.',
      },
      {
        id: 'remi-looks-up',
        triggerAfterMessages: 9999,   // proximity trigger — fires when player walks near Remi
        description: 'Remi notices you and smiles nervously',
        npcId: 'alexs-cousin',
        npcMessage: 'Oh — hi. Sorry, I was just... yeah. You just arrive? I\'m Remi. Alex\'s cousin.',
      },
    ],
    tips: [
      'At parties, most people secretly want to be approached — don\'t hesitate',
      'Ask open questions ("How do you know Alex?") not closed ones',
      'Remember details people share — referencing them later shows you were listening',
      'Explore the different rooms — different types of people in each space',
    ],
  },
]

export function getScenario(id: string): Scenario | undefined {
  return SCENARIOS.find(s => s.id === id)
}

export function getNPC(scenario: Scenario, npcId: string) {
  return scenario.npcs.find(n => n.id === npcId)
}
